name: Chantel Botha
favicon: null
layout_spectrum: 0
typography_spectrum: 0.33427
title: ChantelBotha
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fff3e3'
    - '#d3d0cb'
    - '#9da6a5'
    - '#56aab5'
    - '#348d99'
  brandStrength: 0.5
  lightness: 0.25604963302612305
  saturation: 0.3125
  rhythmicContrast: 0.8137901707086712
purpose: []
